### ISSUE TITLE
 Throws TypeError 

### ISSUE THREAD

**Issue by d3faulter** [cibere/Flow.Launcher.Plugin.PyRepl#4]
### Summary

PyRepl Plugin Throws TypeError When Executing Python Code - json.loads() Receives NoneType. Starts multiple instances of main.py utilizing remaining CPU capacity

### Describe the issue

I'm experiencing a persistent TypeError (version 0.0.3). The plugin attempts to parse the output of executed Python code using json.loads(), but receives a NoneType instead of a valid JSON string. This issue occurs even with simple Python commands like print("Hello World"). Also, several "main.py" instances initiate and take up all remaning CPU capacity.

This is from py print("Hello World"):

[2024-12-09 21:34:25] [DEBUG   ] flogin.jsonrpc.client: Received request: {'jsonrpc': '2.0', 'id': 34, 'method': 'flogin.action.j2LOdYU0xKqQaSa', 'params': [None]}
[2024-12-09 21:34:25] [INFO    ] plugin.result: Starting callback
[2024-12-09 21:34:25] [ERROR   ] flogin.jsonrpc.results: Ignoring exception in result callback (<ReplResult >)
Traceback (most recent call last):
  File "flogin\plugin.py", line 92, in _run_event
  File "plugin\result.py", line 86, in callback
  File "json\__init__.py", line 339, in loads
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
[2024-12-09 21:34:25] [DEBUG   ] flogin.jsonrpc.client: Sending: b'{"jsonrpc": "2.0", "result": {"code": -32603, "message": "Internal error", "data": "the JSON object must be str, bytes or bytearray, not NoneType"}, "id": 34}\r\n'

### Plugin Version

0.0.3

### Flow Launcher Version

1.19.4

### Python Version/Path

C:\Python312\pythonw.exe

### Flow Launcher Log File

[2024-12-09.txt](https://github.com/user-attachments/files/18068041/2024-12-09.txt)

### Flogin Log File

[flogin.log](https://github.com/user-attachments/files/18068045/flogin.log)

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by cibere** [comment]
Hello @d3faulter, thanks for making this report.

As far as the TypeError goes, I am unable to replicate it on `v0.0.3`. What happens if you do `py "Hello World"`?

As for the `main.py` instances, that is an unrelated issue that has also recently come to my attention, which I originally thought was a problem with my laptop, but after seeing that you have the same issue, I will have to debug with flogin to see what is causing this.

**Comment by cibere** [comment]
> As far as the TypeError goes, I am unable to replicate it on `v0.0.3`. What happens if you do `py "Hello World"`?

I was finally able to replicate it, and sent out a path via v0.0.4

**Comment by cibere** [comment]
Moved the CPU issue to #6
